<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>day8</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2edb5548-3721-4533-a287-4bbcab130188</testSuiteGuid>
   <testCaseLink>
      <guid>db786396-3456-40d3-b8d9-5cd11c4d9f41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RecordMode - Copy</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0ec2ff8f-de74-4f69-aa16-43281a98ab71</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/test</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0ec2ff8f-de74-4f69-aa16-43281a98ab71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>10fcbb56-1873-48ff-80ff-46e55dc5666b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0ec2ff8f-de74-4f69-aa16-43281a98ab71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9f724fae-6056-4df2-95bb-5bbe6a999020</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
