<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>healthcare</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>sarwoto.tkr.e@gmail.com;</mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>080df6ad-eefc-4bec-95fc-d6a22be53bae</testSuiteGuid>
   <testCaseLink>
      <guid>b517c809-c916-4e47-b591-c754cd5ef742</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RecordMode - Copy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10fcbb56-1873-48ff-80ff-46e55dc5666b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f724fae-6056-4df2-95bb-5bbe6a999020</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
