<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya, kirim kode</name>
   <tag></tag>
   <elementGuidId>00415d76-3c03-425f-928c-80b23d4525d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TFAJS-1652932518128']/section/div/div[2]/div/div[2]/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mb-8.bl-button.bl-button--primary.bl-button--medium.bl-button--block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>283da79f-919f-4114-85c5-0d3f2699abba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-8 bl-button bl-button--primary bl-button--medium bl-button--block</value>
      <webElementGuid>600202b1-f2e8-4609-9e9e-bc38d73ad675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ya, kirim kode </value>
      <webElementGuid>5f30c2ea-0c95-4b70-9d17-c8d857e5ba3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TFAJS-1652932518128&quot;)/section[1]/div[@class=&quot;bl-modal p-24&quot;]/div[@class=&quot;bl-modal__wrapper&quot;]/div[@class=&quot;bl-card&quot;]/div[@class=&quot;bl-modal__body&quot;]/div[@class=&quot;p-24&quot;]/div[1]/div[1]/div[1]/button[@class=&quot;mb-8 bl-button bl-button--primary bl-button--medium bl-button--block&quot;]</value>
      <webElementGuid>8f465fc7-0722-4969-9145-a61087145b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1652932518128']/section/div/div[2]/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>fe0f00c4-c99f-4595-b25d-24f2e2fe7168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sarwoto.tototkre@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>6fd7f471-946a-4b2b-a79e-8362f3062144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[1]</value>
      <webElementGuid>f4196e70-7325-4964-a3a9-0f07eaaf888f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukan, ganti email'])[1]/preceding::button[1]</value>
      <webElementGuid>8d12488d-d863-4591-8cab-092f221c87c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>747f2d86-3e64-424d-83fc-a2bad37ab1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Ya, kirim kode ' or . = ' Ya, kirim kode ')]</value>
      <webElementGuid>c9b20867-b038-42e0-b3f6-15144758388e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
