<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Peralatan Elektronik</name>
   <tag></tag>
   <elementGuidId>71067ea8-9cd6-4662-be47-daae81d4083b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Level_1_Category_No1']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.hover > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bfcca72-079c-4bb6-af67-535e9e91bcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.home.cate.i0.579953e0XKWhox</value>
      <webElementGuid>d411f48b-962e-4665-b47b-aa0c0a3058e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peralatan Elektronik</value>
      <webElementGuid>0d1562ea-3e2e-4e96-a1a8-3a0c80f84ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Level_1_Category_No1&quot;)/a[@class=&quot;hover&quot;]/span[1]</value>
      <webElementGuid>97cea37c-7f9a-458c-87e8-ebb3ad9304ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='Level_1_Category_No1']/a/span</value>
      <webElementGuid>4ae6f7dd-5935-4bde-8602-f026d82ebbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::span[1]</value>
      <webElementGuid>62637997-e74a-4aa6-b8e4-30420540699c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::span[4]</value>
      <webElementGuid>acf92130-6194-448e-a635-9c52af42c520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksesoris Elektronik'])[1]/preceding::span[1]</value>
      <webElementGuid>9c345b78-e09e-4b67-99b3-1dc53924ab35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion Wanita'])[1]/preceding::span[2]</value>
      <webElementGuid>067b6830-f903-4aba-b91b-54ab0e07f018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Peralatan Elektronik']/parent::*</value>
      <webElementGuid>b9f6517e-25f7-411c-a30c-07a3e00a90cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/ul/li/a/span</value>
      <webElementGuid>ff33045b-208a-4dac-9c2a-d7b64ad786d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Peralatan Elektronik' or . = 'Peralatan Elektronik')]</value>
      <webElementGuid>fb26de11-343d-4c0c-b4c5-9cf811b0010b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
