<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Langkah Strategis Memajukan Sepak Bola In_36bb4e</name>
   <tag></tag>
   <elementGuidId>ce573d5d-3bc6-4d25-aca0-9be2de8828f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>016d118e-cd75-48af-a9e7-7a022e1e4863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>210a2edf-acf2-459f-ba08-0dcd5d02544d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=018212539862037696382:-xa61bkyvao&amp;q=https://bola.kompas.com/read/2014/01/29/0901136/Langkah.Strategis.Memajukan.Sepak.Bola.Indonesia.2%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwjgqKu6lub3AhXJTGwGHc5yB7Y4ChAWegQIAxAC&amp;usg=AOvVaw1J8jjKwTbBqt8QMiAqCK-K</value>
      <webElementGuid>34a2df91-83d4-4ced-a554-b12240233725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>1f6639fb-d33c-468f-9dd9-7359dce63e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>e9c2433d-0ba9-4526-9190-e8f20c43da87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=018212539862037696382:-xa61bkyvao&amp;q=https://bola.kompas.com/read/2014/01/29/0901136/Langkah.Strategis.Memajukan.Sepak.Bola.Indonesia.2%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwjgqKu6lub3AhXJTGwGHc5yB7Y4ChAWegQIAxAC&amp;usg=AOvVaw1J8jjKwTbBqt8QMiAqCK-K</value>
      <webElementGuid>f190aad3-e94e-4630-bce7-5bad9e581cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://bola.kompas.com/read/2014/01/29/0901136/Langkah.Strategis.Memajukan.Sepak.Bola.Indonesia.2?page=all</value>
      <webElementGuid>cdd1b6c3-e1dd-47da-a2ba-1c69b78803b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Langkah Strategis Memajukan Sepak Bola Indonesia (2) Halaman ...</value>
      <webElementGuid>02a88b5f-337b-472a-af96-7707e1763939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>2572a1af-69b9-45c8-b7c2-a921d1a1e1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>f9e618f5-d76e-4d29-abfd-d2ebfe6156d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clipped from Google - 5/2022'])[1]/following::a[1]</value>
      <webElementGuid>bdbefbee-91a0-4da7-b526-ea8d1482338a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sepak-bola'])[2]/following::a[2]</value>
      <webElementGuid>5d003c57-9c58-451f-9527-6ac0546e016e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bola.kompas.com'])[1]/preceding::a[1]</value>
      <webElementGuid>c1b92456-f327-49a6-9775-c4511774563f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Langkah Strategis Memajukan']/parent::*</value>
      <webElementGuid>ee3f596b-6323-4401-85b0-00b30f794463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=018212539862037696382:-xa61bkyvao&amp;q=https://bola.kompas.com/read/2014/01/29/0901136/Langkah.Strategis.Memajukan.Sepak.Bola.Indonesia.2%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwjgqKu6lub3AhXJTGwGHc5yB7Y4ChAWegQIAxAC&amp;usg=AOvVaw1J8jjKwTbBqt8QMiAqCK-K')]</value>
      <webElementGuid>3f48caae-b747-49a4-87b1-8979093371ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>3fb12304-4d4b-45c8-86a3-52f177d608cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=018212539862037696382:-xa61bkyvao&amp;q=https://bola.kompas.com/read/2014/01/29/0901136/Langkah.Strategis.Memajukan.Sepak.Bola.Indonesia.2%3Fpage%3Dall&amp;sa=U&amp;ved=2ahUKEwjgqKu6lub3AhXJTGwGHc5yB7Y4ChAWegQIAxAC&amp;usg=AOvVaw1J8jjKwTbBqt8QMiAqCK-K' and (text() = 'Langkah Strategis Memajukan Sepak Bola Indonesia (2) Halaman ...' or . = 'Langkah Strategis Memajukan Sepak Bola Indonesia (2) Halaman ...')]</value>
      <webElementGuid>19cbca74-e414-415d-b24a-058ac3eff44e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
