<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kgmedia.id_submit</name>
   <tag></tag>
   <elementGuidId>0d603ce0-33fd-42ae-9be1-edf0aa3c3278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87fbd161-d1fe-4ac1-9e2d-38b578cd2dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__button form__button__header</value>
      <webElementGuid>4e70fb41-cb25-4364-b0ed-e0d63ac8019d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7d437db8-c6c0-4f6c-8aef-582c987bf111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d905608d-93b7-44ac-9cc6-2e3fd30c5123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions&quot;]/body[1]/div[@class=&quot;wrap&quot;]/div[@class=&quot;header header--sumpah-pemuda clearfix&quot;]/div[@class=&quot;row clearfix header__wrap&quot;]/div[@class=&quot;container clearfix header__row&quot;]/div[@class=&quot;row col-offset-fluid clearfix&quot;]/div[@class=&quot;col-bs10-5 clearfix&quot;]/form[@class=&quot;search search--header col-bs12-8 col-offset-0&quot;]/input[@class=&quot;form__button form__button__header&quot;]</value>
      <webElementGuid>83922578-a0c0-4237-af47-d648787e1386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit']</value>
      <webElementGuid>8716a1fb-fd8d-4577-b198-19080a23a482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>d7aa4ab5-8ed2-463b-ac07-1d9823dd7069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit']</value>
      <webElementGuid>7b926bfb-bb46-4df8-b61c-a54530bcc103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
