<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Lazada 2022_next-icon next-icon-close nex_6c4a2e</name>
   <tag></tag>
   <elementGuidId>9d627066-c5d5-41af-b5ac-8e6f88f0adb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.next-icon.next-icon-close.next-icon-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a3a2fa85-34b2-4fe2-9216-bbc4adefde48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next-icon next-icon-close next-icon-small</value>
      <webElementGuid>26af9fde-3742-4fb7-9ac4-8601e4d315ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4j.pdp_revamp.0.i1.6835e593kyQbFz</value>
      <webElementGuid>2904f982-af24-46bb-a7f3-1a679cb28c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-layout-column-2&quot;]/div[9]/div[@class=&quot;next-overlay-wrapper next-dialog-wrapper mod-login-dialog-warp opened&quot;]/div[@class=&quot;next-dialog right next-overlay-inner animated fadeInDown mod-login-dialog next-position-cc&quot;]/a[@class=&quot;next-dialog-close&quot;]/i[@class=&quot;next-icon next-icon-close next-icon-small&quot;]</value>
      <webElementGuid>190fc7ed-38ac-4373-abbe-5b63cfde9960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>57512cea-2edb-40c5-bef1-dc6986e40114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
